version: '3.8'

services:
  foyer-app:
    build: .
    image: saraiguess/foyer-app:latest
    container_name: foyer-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://foyer-db:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SERVER_PORT=8081
      - SERVER_SERVLET_CONTEXT-PATH=/Foyer
    depends_on:
      foyer-db:
        condition: service_healthy
    networks:
      - foyer-network
    restart: unless-stopped

  foyer-db:
    image: mysql:8.0
    container_name: foyer-db
    environment:
      - MYSQL_DATABASE=foyer
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - foyer-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - foyer-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  foyer-db-data:

networks:
  foyer-network:
    driver: bridge
